table Calendar
	lineageTag: 72df7e45-1611-5304-9d2f-29be357ea4e9

	column Date
		dataType: dateTime
		formatString: dd mmm yyyy
		lineageTag: 087fce17-dc9d-581f-929a-06d9498b9c77
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d2236c68-836d-5266-b274-76315cf43718
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Start'
		dataType: dateTime
		formatString: mmm yyyy
		lineageTag: eed73a5b-9d86-5846-ae69-e3cae1b44149
		summarizeBy: none
		sourceColumn: Month Start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month No'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 89d6f8d1-5fd6-50c7-8de5-48b23a2629e0
		summarizeBy: none
		sourceColumn: Month No

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 4e3118f0-9939-5ea8-b4a1-e14ff405a289
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Month No'

		annotation SummarizationSetBy = Automatic

	partition Calendar = m
		mode: import
		source =
				let
				    // 1 Jan 2019 up to the last full day in the prepared data
				    G = Parquet.Document(File.Contents("C:\Users\emira\Projects\GitHub-Projects\GermanEnergyDashboard\data\dashboard\power_daily.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    StartDate = #date(2019, 1, 1),
				    EndDate = Date.From(List.Max(G[date])),
				    Dates = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
				    #"To Table" = Table.FromList(Dates, Splitter.SplitByNothing(), {"Date"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"To Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Month Start" = Table.AddColumn(#"Added Year", "Month Start", each Date.StartOfMonth([Date]), type date),
				    #"Added Month No" = Table.AddColumn(#"Added Month Start", "Month No", each Date.Month([Date]), Int64.Type),
				    #"Added Month" = Table.AddColumn(#"Added Month No", "Month", each Date.ToText([Date], "MMM", "en-GB"), type text)
				in
				    #"Added Month"

	annotation PBI_ResultType = Table

